/* eslint-disable @typescript-eslint/no-empty-function */
export const defaultAppCTX = {
  properties: [],
  propertyInner: null,
  about: {},
  offices: [],
  agents: [],
  agentsInner: null,
  blogs: [],
  blogsInner: null,
  location: [],
  propertyCategory: [],
  dealType: [],
  selectedDealType: [],
  selectedPropertyCategory: [],
  selectedLocation: [],
  searchInput: null,
  setSelectedDealType: () => {},
  setSelectedPropertyCategory: () => {},
  setSelectedLocation: () => {},
  fetchPropertyInnerData: () => {},
  fetchPropertiesData: () => {},
  fetchAboutData: () => {},
  fetchOfficesData: () => {},
  fetchAgentsData: () => {},
  fetchAgentsInnerData: () => {},
  fetchBlogsData: () => {},
  fetchBlogsInnerData: () => {},
  fetchLocationData: () => {},
  fetchPropertyCategoryData: () => {},
  fetchDealTypeData: () => {},
  setSearchInput: () => {},
  createCustomerRequest: () => {}
}
